name: Run TestNG Tests Hourly Every Day In The Morning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7-12 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '19'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests using Gradle
      run: ./gradlew test --info -Dusername=${{ secrets.MONSTER_USERNAME }} -Dpassword=${{ secrets.MONSTER_PASSWORD }}
